version: 2
updates:
  - package-ecosystem: "npm"
    directory: "my-blog/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
      time: "00:00"
    target-branch: "main"
    # dependabotのpull requestを実質無制限にする
    open-pull-requests-limit: 10000
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
      time: "00:00"
    target-branch: "main"
    # dependabotのpull requestを実質無制限にする
    open-pull-requests-limit: 10000