name: Deploy Astro blog to Cloudflare Pages

on:
  push:
    branches:
      - main # main ブランチに push されたら自動でデプロイ
  workflow_dispatch:
    # 手動でワークフローを実行するときに使用

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    # 実行環境は Ubuntu 22.04 LTS
    defaults:
      run:
        working-directory: my-blog
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: my-blog/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Cloudflare Pages
        uses: cloudflare/wranger-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: Ettotto_CTF
          directory: ../../my-blog/dist
          branch: main

