name: Deploy Astro blog to Cloudflare Pages

on:
  push:
    branches:
      - main # main ブランチに push されたら自動でデプロイ
  workflow_dispatch:
    # 手動でワークフローを実行するときに使用

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    # 実行環境は Ubuntu 22.04 LTS
    environment: CLOUDFLARE_API_TOKEN
    defaults:
      run:
        working-directory: my-blog
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: my-blog/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: install latest wrangler
        run: npm install -g wrangler@latest

      - name: Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy my-blog/dist --branch main --project-name ettottoctf001
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

